print('Zum addiren von 3 Werten deine erste eingabe: ')
first1 = input()
print('Zum addiren von 3 Werten deine zweie eingabe: ')
first2 = input()
print('Zum addiren von 3 Werten deine drite eingabe: ')
first3 = input()
print('Zum addiren von 3 Werten deine erste eingabe: ')
print('Cumme ist ' + first1 +first2 + first3)
